### ISSUE TITLE
Cannot open http://0.0.0.0:4567 in Chrome

### ISSUE THREAD

**Issue by IsmailM** [yannickwurm/sequenceserver#158]
I cannot open `http://0.0.0.0:4567` in the latest version of chrome (on yosemite); rather it opens up the Google search results of the query http://0.0.0.0:4567...

`http://localhost:4567` works fine...

Perhaps we should stick with `localhost:4567` if it is more reliable...

**Comment by IsmailM** [comment]
There seems to be a quite a few Issues opened on Chromium with regards to this. I think they are planning on a fix... 

https://code.google.com/p/chromium/issues/detail?id=428046

Nevertheless, despite a fix was promised over a month ago; the problem is still here in Chrome Canary (which is two versions newer than the latest chrome)...

So, it may be some time before a fix actually comes into place...

**Comment by yeban** [comment]
Agreed. Can you take care of this?
