### ISSUE TITLE
-h, --host argument command line arg. cannot be used due to conflict

### ISSUE THREAD

**Issue by IsmailM** [yannickwurm/sequenceserver#162]
Currently it's not possible to use the `-h` or `--host` command line arguments due to a conflict with `-h` (help text)...

The easiest fix would be to have no shorthand (i.e. remove just the `-h`)....

**Comment by yeban** [comment]
Good catch. Thanks! I had totally forgotten about it. How about using `-H` as shortcut?

**Comment by IsmailM** [comment]
Yep, good idea... I've updated the PR #163
