### ISSUE TITLE
rescue in SequenceServer.run is too greedy

### ISSUE THREAD

**Issue by yeban** [yannickwurm/sequenceserver#168]
It rescues all kinds of error thinking it's port conflict.

**Comment by IsmailM** [comment]
I agree... Maybe a check in SS.init

```
`netstat -an | grep #{config[:port]}`
```

**Comment by yeban** [comment]
I think failing to bind to a port is the best way to determine its availability. It is possible that in the time you query availability and bind some other process occupies the port. Then, a port may be available but not bindable unless root requiring further checks. And why do mature servers like Thin and Puma don't do this automagically?

The intent of this issue is to rescue only specific errors raised by Thin if it failed to bind and leave any other issue to be handled by the last error handler in bin/sequenceserver.

**Comment by yeban** [comment]
closed via 508e7155750f8ef7a97c4aba58dcc8a758784811
