### ISSUE TITLE
screen resize issue

### ISSUE THREAD

**Issue by yannickwurm** [yannickwurm/sequenceserver#173]
There's a small transition period with snafu (e.g. at ~1 seconds and ~11 seconds)

https://www.youtube.com/watch?v=EJxfIclhxVA

**Comment by IsmailM** [comment]
This is due to the SVG not being responsive... (I raised this issue here: #157)...

I started on a [PR](https://github.com/IsmailM/sequenceserver/tree/responsive_SVGs); which is working (but then stops working on clicking on View More/ View less - however fixing that should be relatively easy)...
