### ISSUE TITLE
Fasta Downloads

### ISSUE THREAD

**Issue by zachcp** [yannickwurm/sequenceserver#185]
Hi Team Sequence Server,

Thanks for developing this great software. I've encountered an error when trying to download fasta files of the blast hits where the downloaded fasta file has the following text:

```
# ERROR: incorrect number of sequences found.
# You requested 1 sequence(s) with the following identifiers:
#   399
# from the following databases:
#  Test FNA Database 
# but we found 0 sequence(s).
# 
# This is likley due to a problem with how databases are formatted.
# Please share this text with the person managing this website (or
# https://groups.google.com/forum/?fromgroups#!forum/sequenceserver
# if you are the admin) so that the issue can be resolved.
# 
# If any sequences were retrieved, you can find them below
# (but some may be incorrect, so be careful!)
```

This is a simple database formatted using `makeblastdb`. Any suggestions on how to format the DBs to make them compatible with Sequence Server? Also I notice that you have disable downloading of all hits as a fasta but not individual hits. Perhaps you are already checking the DB for compatability? Maybe the individual fasta links should also be toggled off.

![screen shot 2015-03-25 at 4 54 44 pm](https://cloud.githubusercontent.com/assets/1260667/6835348/771402da-d310-11e4-9a15-0af6ea5e8636.PNG)

Thanks again,
zach cp

**Comment by vivekiitkgp** [comment]
Hey Zach,

To answer your query about disabled links, there are few things I'd like to
tell you:

1. The `FASTA of all hits` is disabled by default when there are more than
30 hits obtained.
2. The `FASTA of selected hit(s)` link is active only when you select one
or more hits (again deactivates when more than 30 hits are selected)

Thus, the active FASTA download button on all hits is for you to be able to
download only selective hits as and when needed. This helps you to bypass
the above limitations at the cost of some effort.

We do have plans to assist users in establishing database integrity but
there is no mechanism in place as of now.

Thanks for reaching out to us!

-- Vivek

**Comment by zachcp** [comment]
thanks vivek


On Mar 25, 2015, at 5:26 PM, Vivek Rai <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey Zach,

To answer your query about disabled links, there are few things I'd like to
tell you:

1. The `FASTA of all hits` is disabled by default when there are more than
30 hits obtained.
2. The `FASTA of selected hit(s)` link is active only when you select one
or more hits (again deactivates when more than 30 hits are selected)

Thus, the active FASTA download button on all hits is for you to be able to
download only selective hits as and when needed. This helps you to bypass
the above limitations at the cost of some effort.

We do have plans to assist users in establishing database integrity but
there is no mechanism in place as of now.

Thanks for reaching out to us!

-- Vivek

On Thu, Mar 26, 2015 at 2:31 AM zachcp <notifications@github.com<mailto:notifications@github.com>> wrote:

> Hi Team Sequence Server,
>
> Thanks for developing this great software. I've encountered an error when
> trying to download fasta files of the blast hits where the downloaded fasta
> file has the following text:
>
> # ERROR: incorrect number of sequences found.
> # You requested 1 sequence(s) with the following identifiers:
> # 399
> # from the following databases:
> # Test FNA Database
> # but we found 0 sequence(s).
> #
> # This is likley due to a problem with how databases are formatted.
> # Please share this text with the person managing this website (or
> # https://groups.google.com/forum/?fromgroups#!forum/sequenceserver
> # if you are the admin) so that the issue can be resolved.
> #
> # If any sequences were retrieved, you can find them below
> # (but some may be incorrect, so be careful!)
>
> This is a simple database formatted using makeblastdb. Any suggestions on
> how to format the DBs to make them compatible with Sequence Server? Also I
> notice that you have disable downloading of all hits as a fasta but not
> individual hits. Perhaps you are already checking the DB for compatability?
> Maybe the individual fasta links should also be toggled off.
>
> [image: screen shot 2015-03-25 at 4 54 44 pm]
> <https://cloud.githubusercontent.com/assets/1260667/6835348/771402da-d310-11e4-9a15-0af6ea5e8636.PNG>
>
> Thanks again,
> zach cp
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yannickwurm/sequenceserver/issues/185>.
>

—
Reply to this email directly or view it on GitHub<https://github.com/yannickwurm/sequenceserver/issues/185#issuecomment-86223972>.

Zach Charlop-Powers
Post-Doctoral Fellow
Laboratory of Genetically Encoded Small Molecules
Rockefeller University

zcharlop@rockefeller.edu<mailto:zcharlop@rockefeller.edu>
zachcp.org

BradyLab:         http://lab.rockefeller.edu/brady/research
DrugsfromDirt:  http://drugsfromdirt.org/
eSNaPD:           http://esnapd2.rockefeller.edu/

**Comment by yannickwurm** [comment]
@vivekiitkgp could you please add what you explained to the faq? 

Hey @zachcp thanks for the kind words. We generally see your type of issue occurring either when the database in one of the following 3 cases: 
 1. old database (blast sometimes is incompatible with itself)
 2. weird sequence identifiers (either there are some duplicate names or funky $\\t.^| characters)
 3. `-parse_seqids` wasn't used

I suggest you try extracting the relevant sequence from your datasbase using `blastdbcmd`... if it shows a bunch of error messages that might clarify what's going on. 

Cheers y

**Comment by zachcp** [comment]
So it turns out that I was not using `-parse-seqids` which is necessary. But even after using parse seqIDs, I run into an issue. If you do not have your fasta headers in the same format as NCBI, you will encounter issues.  I'm going to file a seperate feature request....

**Comment by yeban** [comment]
If you running into the same issue even after using `-parse_seqids` it is because sequence retrieval doesn't work with numeric ids. And in the error message you posted the sequence id is 399. It's a bug in BLAST+, not SequenceServer. See #88. We recommend prefixing a mnemonic string to your ids.

**Comment by zachcp** [comment]
Hi @yeban,

indeed, that was an issue; I renamed my records, reformatted and retrieval now works great.

thanks.
