### ISSUE TITLE
Feature Request: Allow Custom Fasta Headers

### ISSUE THREAD

**Issue by zachcp** [yannickwurm/sequenceserver#186]
I have been using `sequenceserver` for sequences generated in our lab that are not destined for NCBI and are therefore not in the `gi | xxx | gb | xxx | name` format. In fact we often use the fastaheader to keep track of information about how the sequence was processed: SampleID, run info, or whatever; usually separated by an underscore.

Although `sequenceserver` can display the blast results just fine, it cannot recover the fasta results on unconventionally named files (see #185 ). However, I believe there might be a simple workaround. Consider the following example:
```
#make a simple fasta
printf ">seq1\nAAACTT\n>seq 2\nACTCTCTC\n>name_with_underscore\nACACACTTTTC\>funny@#name\nACTCATAC" > test.fa

#create a blast db from it
makeblastdb -dbtype nucl -in test.fa -parse_seqids

#recover the sequences from it
blastdbcmd -db 'test.fa' -entry 'seq1'                  #works
>lcl|seq1 
AAACTT
blastdbcmd -db 'test.fa' -entry 'name_with_underscore'  #works
blastdbcmd -db 'test.fa' -entry 'funny@#name'           #works
blastdbcmd -db 'test.fa' -entry 'seq 2'                 #error
blastdbcmd -db 'test.fa' -entry 'seq'                   #returns seq 2
>lcl|seq 2
ACTCTCTC

#note ! and $ may work but cause problems in the shell
```
It looks like just about any names that don't have spaces can be correctly recovered by `blastdbcmd`. Whats happening when you parse these results? It looks as if all of the wrangling bits are handled in the `Sequence` class. Could you accomadate non NCBI-lie sequences just by doing a bit of parsing? Something like:

```[ruby]
#replace this:
Sequence = Struct.new(:gi, :seqid, :accession, :title, :value) do
   def initialize(*args)
     args[0] = nil if args[0] == 'N/A'
     super
   end

#with something like:
 Sequence = Struct.new(:gi, :seqid, :accession, :title, :value) do
   def initialize(*args)

    #this bit is pseudocode that assumes
    #two values are passed as output  instead of five.
    if length(args) <  5 and args[0] == 'lcl| ':
               #set gi to nothing
                args[0] = nil  
                #set seqid, accession and title to the sequence name
                args[1] = args[0] 
                args[2] = args[0]
                args[3] = args[0]
                #set the value of the sequence
                args[4] = args[1]
     super
   end
```

Or, better, by parsing/error before initializing a `Sequence`  you could accommodate check for ncbi format,  `lcl` tags etc and pass the correct values.

Let me know if you want me to give a try.  I'm not too familiar with the codebase (although its well organized) and don't really know Ruby so I imagine one of you could implement it a lot faster. But if you're overbooked and interested, I could give it a go: this would be a very useful feature for us.

Thanks again,
zach cp

**Comment by yeban** [comment]
SequenceServer doesn't assume NCBI like ids. In fact, using pipe in your sequence ids is not recommended. For example, if your sequence id in FASTA file is `abc|def`, the retrieved sequence will have the id `gnl|def` :/. And pre- BLAST+ 2.2.30 (or 29? don't remember), `abc|` in your sequence id would cause `makeblastdb` to fail. `Sequence` class tries to accommodate both cases: NCBI like and non-NCBI like ids. When I say 'NCBI like', I only mean 'nr' and 'nt' dbs.

I don't exactly understand the issue here. What did you expect to see and what did  SequenceServer give? If you are referring to the exact same issue as #185 please see my comment on that issue.

**Comment by zachcp** [comment]
@yeban Thanks for your quick response.

I'm sorry if I was not clear: my issue was that fasta retrieval did not work for me using locally formatted databases.  The rest of the post was trying to pin down the issue which I erroneously believed to be in the parsing of  the output of `blastdbcmd` prior to calling `Sequence`.

However, I just looked at #88, reformatted my fasta headers to eliminate numbers and now fasta retrieval seems to work fine.  

So it seems I may have also been bitten by that indexing bug. Thanks again,
zach cp
