### ISSUE TITLE
ping-back

### ISSUE THREAD

**Issue by yannickwurm** [yannickwurm/sequenceserver#33]
add a “ping-back” to see who is using/installing the server where? (or interactively ask for email address when user is running it the first time & ask them for permission to share that info with us)

Why?

* we get a better idea of number of users
* and can keep them up to date on developments

**Comment by yeban** [comment]
I don't think the effort is worth it. And I definitely won't be the one implementing it.

1. The are several channels to keep the users who care up to date (mailing list, Twitter, etc.).
2. Along with the number of instances out in the wild, I think we should try and collect data as outlined in #180. 

I recommend closing this issue.
