### ISSUE TITLE
Output customization & text download & text input

### ISSUE THREAD

**Issue by yannickwurm** [yannickwurm/sequenceserver#78]
Dr. Massimiliano Babbucci from University of Padova writes:

> I just tried your program "SequenceServer" and I think that it's very interesting and usefull...I have a question...It's possible,or it will be in the next relase, to save the blast results in a txt file with the powerfull option of blast+, for example with the several  -outfmt parameters?
> And I think that it would be very interesting to have the option of using txt file as input as well as the "copy and paste"

So that's three things: 

 * download the output as a text file
 * use a text file for input. (if we do this it should be drag and drop onto the text area (like when you do a google image search with an image), not a separate/alternative item in the submission form.
 * customize output format ( via -outfmt parameters)

**Comment by yeban** [comment]
Closing notes:
1. Can download FASTA of one or more hits, upto 30 hits at a time (see #89).
2. Can download XML of the entire result.
3. Can download TSV with 'standard' (12) columns or 'full' (all 30 or so columns).

We don't support customising TSV via `-outfmt`. Users must filter their TSV downstream.

Downloading results in other formats is technically possible, but not exposed through our UI. We will evaluate and other formats if there's a demand.
