### ISSUE TITLE
Job Queing

### ISSUE THREAD

**Issue by xiy** [yannickwurm/sequenceserver#96]
(Feature, Low Priority)

Not sure if this has been brought up before but I'm sure a lot of people would like the ability to queue BLAST jobs up, similar to the official service, and get a unique ID to refer back to the results.

This could be easily implemented with Resque/Redis.

Probably pretty low priority at the moment but just an idea. Thoughts?

**Comment by malcook** [comment]
You might consider decoupling FE/BE by implementing NCBI's URL API   
http://www.ncbi.nlm.nih.gov/BLAST/Doc/urlapi.html

Doing so would enable other blast clients, both UIs and libraries, to nicely interoperate.  Imagine:  a SS site whose content is also exposed by  URL API implemented by you potentially allowing usage by: 
Vector NTI 
biopython
... more

**Comment by yeban** [comment]
Closing this in favour of #181. We won't ever implement a full-blow queuing system within SequenceServer. And the new URL API will likely take a much simpler approach than NCBI's (/rid -> html results, /rid.xml -> XML results, /rid.tsv -> tabular results).

**Comment by malcook** [comment]
+1 for dropping the full-blown queuing system
-1 for not adopting the NCBI's URL API.  We're you to adopt it, sequence
server would be inter-operable with other clients that employ this URL API
(such as Vector NTI Advanced).

Just sayin'

+100 for sequencserver in the first place

~ Malcolm Cook
h: 913.642.5257
m: 913.226.1542
w: 816.926.4449

**Comment by yeban** [comment]
Thanks for your input, @malcook. And I hope you will continue to remain involved :). I think a strong case for interop can really be made if our user base grows 1000 fold. In the meantime our focus is on simple things - improve the search UX (database widget, advanced params) and make incremental refinements to the results (visualisations, taxonomy data).

**Comment by malcook** [comment]
Fair enough.
So, not -1 then.
Only -.001  ;)
Thanks!

~ Malcolm Cook
h: 913.642.5257
m: 913.226.1542
w: 816.926.4449
